data:
  - id: _pool
    type: http
    source: clash
    target: clash
    urls:
      - https://raw.githubusercontent.com/dongchengjie/airport/main/subs/_pool.yaml
    output: subs/_pool.yaml
  - id: aiboboxx
    type: http
    source: v2ray
    target: clash
    urls:
      - https://raw.githubusercontent.com/aiboboxx/v2rayfree/main/v2
    output: subs/aiboboxx.yaml
  - id: anaer
    type: http
    source: clash
    target: clash
    urls:
      - https://raw.githubusercontent.com/anaer/Sub/main/clash.yaml
    output: subs/anaer.yaml
  - id: changfengoss
    type: github
    source: clash
    target: clash
    urls:
      - https://github.com/changfengoss/pub
    output: subs/changfengoss.yaml
    options:
      span: 1209600000
      exts: .yaml
  - id: chengaopan
    type: http
    source: clash
    target: clash
    urls:
      - https://raw.githubusercontent.com/chengaopan/AutoMergePublicNodes/master/list.yml
    output: subs/chengaopan.yaml
  - id: hkaa0
    type: http
    source: clash
    target: clash
    urls:
      - https://raw.githubusercontent.com/hkaa0/permalink/main/proxy/clash.yaml
    output: subs/hkaa0.yaml
  - id: mahdibland
    type: http
    source: clash
    target: clash
    urls:
      - https://raw.githubusercontent.com/mahdibland/ShadowsocksAggregator/master/Eternity.yml
      - https://raw.githubusercontent.com/mahdibland/ShadowsocksAggregator/master/EternityAir.yml
    output: subs/mahdibland.yaml
  - id: peasoft
    type: http
    source: v2ray
    target: clash
    urls:
      - https://raw.githubusercontent.com/peasoft/NoMoreWalls/refs/heads/master/list.yml
    output: subs/peasoft.yaml
  - id: ripaojiedian
    type: http
    source: v2ray
    target: clash
    urls:
      - https://raw.githubusercontent.com/ripaojiedian/freenode/main/sub
    output: subs/ripaojiedian.yaml
  - id: soroushmirzaei
    type: http
    source: v2ray
    target: clash
    urls:
      - https://raw.githubusercontent.com/soroushmirzaei/telegram-configs-collector/main/channels/networks/grpc
      - https://raw.githubusercontent.com/soroushmirzaei/telegram-configs-collector/main/channels/networks/http
      - https://raw.githubusercontent.com/soroushmirzaei/telegram-configs-collector/main/channels/networks/tcp
      - https://raw.githubusercontent.com/soroushmirzaei/telegram-configs-collector/main/channels/networks/ws
      - https://raw.githubusercontent.com/soroushmirzaei/telegram-configs-collector/main/networks/grpc
      - https://raw.githubusercontent.com/soroushmirzaei/telegram-configs-collector/main/networks/http
      - https://raw.githubusercontent.com/soroushmirzaei/telegram-configs-collector/main/networks/tcp
      - https://raw.githubusercontent.com/soroushmirzaei/telegram-configs-collector/main/networks/ws
      - https://raw.githubusercontent.com/soroushmirzaei/telegram-configs-collector/main/subscribe/networks/grpc
      - https://raw.githubusercontent.com/soroushmirzaei/telegram-configs-collector/main/subscribe/networks/http
      - https://raw.githubusercontent.com/soroushmirzaei/telegram-configs-collector/main/subscribe/networks/tcp
      - https://raw.githubusercontent.com/soroushmirzaei/telegram-configs-collector/main/subscribe/networks/ws
    output: subs/soroushmirzaei.yaml
  - id: tssf
    type: http
    source: clash
    target: clash
    urls:
      - https://raw.githubusercontent.com/ts-sf/fly/main/clash
    output: subs/tssf.yaml
  - id: ttvg
    type: http
    source: clash
    target: clash
    urls:
      - https://tt.vg/freeclash
    output: subs/ttvg.yaml
  - id: xrayvip
    type: http
    source: clash
    target: clash
    urls:
      - https://www.xrayvip.com/free.yaml
    output: subs/xrayvip.yaml
  - id: yudou
    type: http
    source: clash
    target: clash
    urls:
      - https://raw.githubusercontent.com/dongchengjie/proxy-crawler/main/subscriptions/yudou.yaml
    output: subs/yudou.yaml
  - id: zhangkaiitugithub
    type: http
    source: clash
    target: clash
    urls:
      - https://raw.githubusercontent.com/zhangkaiitugithub/passcro/main/speednodes.yaml
    output: subs/zhangkaiitugithub.yaml
  - id: Pawdroid
    type: http
    source: v2ray
    target: clash
    urls:
      - https://raw.githubusercontent.com/Pawdroid/Free-servers/refs/heads/main/sub
    output: subs/Pawdroid.yaml
  - id: ermaozi
    type: http
    source: clash
    target: clash
    urls:
      - https://raw.githubusercontent.com/ermaozi/get_subscribe/main/subscribe/clash.yml
      - https://raw.githubusercontent.com/ermaozi01/free_clash_vpn/main/subscribe/clash.yml
    output: subs/ermaozi.yaml
  - id: coldwater-10
    type: http
    source: v2ray
    target: clash
    urls:
      - https://raw.githubusercontent.com/coldwater-10/V2ray-Config/main/Sub1.txt
      - https://raw.githubusercontent.com/coldwater-10/V2ray-Config/main/Sub2.txt
      - https://raw.githubusercontent.com/coldwater-10/V2ray-Config/main/Sub3.txt
      - https://raw.githubusercontent.com/coldwater-10/V2ray-Config/main/Sub4.txt
      - https://raw.githubusercontent.com/coldwater-10/V2ray-Config/main/Sub5.txt
      - https://raw.githubusercontent.com/coldwater-10/V2ray-Config/main/Sub6.txt
      - https://raw.githubusercontent.com/coldwater-10/V2ray-Config/main/Sub7.txt
      - https://raw.githubusercontent.com/coldwater-10/V2ray-Config/main/Sub8.txt
      - https://raw.githubusercontent.com/coldwater-10/V2ray-Config/main/Sub9.txt
      - https://raw.githubusercontent.com/coldwater-10/V2ray-Config/main/Sub10.txt
    output: subs/coldwater-10.yaml
  - id: snakem982
    type: http
    source: clash
    target: clash
    urls:
      - https://raw.githubusercontent.com/snakem982/proxypool/main/source/clash-meta.yaml
      - https://raw.githubusercontent.com/snakem982/proxypool/main/source/clash-meta-2.yaml
    output: subs/snakem982.yaml
  - id: ripaojiedian
    type: http
    source: clash
    target: clash
    urls:
      - https://raw.githubusercontent.com/ripaojiedian/freenode/refs/heads/main/clash
    output: subs/ripaojiedian.yaml
  - id: clashfree
    type: github
    source: clash
    target: clash
    urls:
      - https://github.com/clashfree/clashfree.github.io
    output: subs/clashfree.yaml
    options:
      span: 1209600000
      exts: .yaml
  - id: trial
    type: post-http
    source: clash
    target: clash
    urls:
      - https://raw.githubusercontent.com/abshare/abshare.github.io/refs/heads/main/README.md
      - https://raw.githubusercontent.com/abshare3/abshare3.github.io/refs/heads/main/README.md
      - https://raw.githubusercontent.com/tolinkshare2/tolinkshare2.github.io/refs/heads/main/README.md
      - https://raw.githubusercontent.com/toshare5/toshare5.github.io/refs/heads/main/README.md
      - https://raw.githubusercontent.com/mkshare3/mkshare3.github.io/refs/heads/main/README.md
      - https://raw.githubusercontent.com/mksshare/mksshare.github.io/refs/heads/main/README.md
    output: subs/trial.yaml
    options:
      func: (str)=>[str.replaceAll("\n","").replaceAll("\r","").split("Clash订阅链接")[1].split("```").filter(Boolean)[0].concat("?flag=clash")]
  - id: SFZY666
    type: http
    source: clash
    target: clash
    urls:
      - https://raw.githubusercontent.com/dongchengjie/proxy-crawler/main/subscriptions/SFZY666.yaml
    output: subs/SFZY666.yaml
  - id: blue-Youtube
    type: http
    source: clash
    target: clash
    urls:
      - https://raw.githubusercontent.com/dongchengjie/proxy-crawler/main/subscriptions/blue-Youtube.yaml
    output: subs/blue-Youtube.yaml
  - id: hkaa0
    type: post-http
    source: v2ray
    target: clash
    urls:
      - https://tgstat.com/channel/@hkaa0
    output: subs/hkaa0.yaml
    options:
      func: (str)=>str.match(/https?:\/\/[^\s"<']+/mg)
